import type { Icon } from "@phosphor-icons/react";
import {
  AddressBookIcon,
  AlarmIcon,
  ArchiveIcon,
  ArrowCounterClockwiseIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowSquareOutIcon,
  ArrowUUpLeftIcon,
  ArrowUUpRightIcon,
  ArrowUpIcon,
  ArrowsClockwiseIcon,
  AtIcon,
  BankIcon,
  BarcodeIcon,
  BellIcon,
  BellRingingIcon,
  BellSlashIcon,
  BinocularsIcon,
  BookIcon,
  BookOpenIcon,
  BookmarkSimpleIcon,
  BrainIcon,
  BriefcaseIcon,
  BroadcastIcon,
  BrowserIcon,
  BrowsersIcon,
  BugIcon,
  BuildingsIcon,
  CalculatorIcon,
  CalendarBlankIcon,
  CalendarIcon,
  CameraIcon,
  CaretDoubleDownIcon,
  CaretDoubleUpIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  ChartBarHorizontalIcon,
  ChartBarIcon,
  ChartDonutIcon,
  ChartLineDownIcon,
  ChartLineIcon,
  ChartLineUpIcon,
  ChartPieIcon,
  ChartPieSliceIcon,
  ChartScatterIcon,
  ChatCircleIcon,
  ChatTextIcon,
  ChatsIcon,
  CheckCircleIcon,
  CheckIcon,
  CheckSquareIcon,
  CircleNotchIcon,
  CircuitryIcon,
  ClipboardIcon,
  ClipboardTextIcon,
  ClockIcon,
  CloudArrowDownIcon,
  CloudArrowUpIcon,
  CloudCheckIcon,
  CodeBlockIcon,
  CodeIcon,
  CoinsIcon,
  ColumnsIcon,
  CommandIcon,
  CompassIcon,
  CopyIcon,
  CpuIcon,
  CreditCardIcon,
  CrosshairIcon,
  CubeIcon,
  CurrencyBtcIcon,
  CurrencyCircleDollarIcon,
  CurrencyDollarIcon,
  CurrencyEurIcon,
  CurrencyKrwIcon,
  DatabaseIcon,
  DesktopIcon,
  DeviceMobileIcon,
  DotsSixVerticalIcon,
  DotsThreeIcon,
  DotsThreeVerticalIcon,
  DownloadSimpleIcon,
  EnvelopeIcon,
  EnvelopeSimpleIcon,
  ExportIcon,
  EyeIcon,
  EyeSlashIcon,
  EyedropperIcon,
  FadersIcon,
  FastForwardIcon,
  FileCodeIcon,
  FileCsvIcon,
  FileIcon,
  FilePdfIcon,
  FileTextIcon,
  FileZipIcon,
  FilmSlateIcon,
  FingerprintIcon,
  FireIcon,
  FloppyDiskIcon,
  FolderIcon,
  FolderOpenIcon,
  FunnelIcon,
  GaugeIcon,
  GearIcon,
  GearSixIcon,
  GiftIcon,
  GitBranchIcon,
  GitCommitIcon,
  GitMergeIcon,
  GitPullRequestIcon,
  GithubLogoIcon,
  GitlabLogoIcon,
  GlobeIcon,
  GraphIcon,
  HandshakeIcon,
  HardDriveIcon,
  HardDrivesIcon,
  HeadphonesIcon,
  HeartIcon,
  HeartbeatIcon,
  HourglassIcon,
  HouseIcon,
  IdentificationCardIcon,
  ImageIcon,
  InfoIcon,
  KeyIcon,
  KeyboardIcon,
  LaptopIcon,
  LightbulbIcon,
  LightningIcon,
  LinkBreakIcon,
  LinkIcon,
  ListIcon,
  LockIcon,
  LockOpenIcon,
  MagicWandIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  MapTrifoldIcon,
  MegaphoneIcon,
  MicrophoneIcon,
  MicrophoneSlashIcon,
  MinusCircleIcon,
  MinusIcon,
  MoneyIcon,
  MoonIcon,
  MusicNoteIcon,
  MusicNotesIcon,
  NavigationArrowIcon,
  NoteIcon,
  NotebookIcon,
  PackageIcon,
  PaintBrushIcon,
  PaletteIcon,
  PaperPlaneRightIcon,
  PaperPlaneTiltIcon,
  PaperclipIcon,
  PathIcon,
  PauseIcon,
  PencilIcon,
  PencilSimpleIcon,
  PercentIcon,
  PhoneCallIcon,
  PhoneIcon,
  PiggyBankIcon,
  PlayIcon,
  PlaylistIcon,
  PlugIcon,
  PlugsConnectedIcon,
  PlugsIcon,
  PlusCircleIcon,
  PlusIcon,
  PowerIcon,
  PrinterIcon,
  ProhibitIcon,
  PulseIcon,
  PushPinIcon,
  QrCodeIcon,
  QuestionIcon,
  QuotesIcon,
  ReceiptIcon,
  RewindIcon,
  RobotIcon,
  RowsIcon,
  ScalesIcon,
  ScreencastIcon,
  SealCheckIcon,
  SealWarningIcon,
  ShareNetworkIcon,
  ShieldCheckIcon,
  ShieldIcon,
  ShieldWarningIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SidebarSimpleIcon,
  SigmaIcon,
  SignInIcon,
  SignOutIcon,
  SkipBackIcon,
  SkipForwardIcon,
  SlidersHorizontalIcon,
  SlidersIcon,
  SparkleIcon,
  SpeakerHighIcon,
  SpeakerLowIcon,
  SpeakerSlashIcon,
  SpinnerGapIcon,
  SpinnerIcon,
  SquaresFourIcon,
  StackIcon,
  StackSimpleIcon,
  StarIcon,
  StopIcon,
  StorefrontIcon,
  SunIcon,
  SwatchesIcon,
  TableIcon,
  TagIcon,
  TargetIcon,
  TelevisionIcon,
  TerminalIcon,
  TerminalWindowIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  TicketIcon,
  TimerIcon,
  ToolboxIcon,
  TranslateIcon,
  TrashIcon,
  TrashSimpleIcon,
  TreeStructureIcon,
  TrendDownIcon,
  TrendUpIcon,
  TruckIcon,
  UploadSimpleIcon,
  UserCircleIcon,
  UserIcon,
  UserPlusIcon,
  UsersIcon,
  UsersThreeIcon,
  VideoCameraIcon,
  VideoIcon,
  WalletIcon,
  WarningCircleIcon,
  WarningIcon,
  WarningOctagonIcon,
  WaveformIcon,
  WifiHighIcon,
  WifiSlashIcon,
  WrenchIcon,
  XCircleIcon,
  XIcon,
  XSquareIcon,
} from "@phosphor-icons/react/dist/ssr";

/**
 * Phosphor 아이콘 큐레이션 카탈로그 — 단일 진실원천(#66).
 *
 * /icons 검색 갤러리와 components/icon-picker.tsx 가 공유한다.
 * 전체 1,500여 종을 번들하지 않고 실사용 빈도 높은 250+종만 등록한다 —
 * 여기 없는 아이콘은 phosphoricons.com 에서 찾은 뒤 동일한 import 규칙
 * (`@phosphor-icons/react/dist/ssr`)으로 쓰면 된다.
 *
 * 항목 추가 시: 공식 컴포넌트명(…Icon 접미사) + 영문/한글 keywords 를 함께
 * 등록한다. 존재하지 않는 이름은 typecheck 가, 형식은 catalog.test.ts 가 잡는다.
 */
export type IconCategory =
  | "navigation"
  | "action"
  | "object"
  | "communication"
  | "media"
  | "chart"
  | "finance"
  | "status"
  | "system";

export const ICON_CATEGORIES: { key: IconCategory; label: string }[] = [
  { key: "navigation", label: "내비게이션" },
  { key: "action", label: "액션·편집" },
  { key: "object", label: "사물·파일" },
  { key: "communication", label: "커뮤니케이션" },
  { key: "media", label: "미디어" },
  { key: "chart", label: "차트·데이터" },
  { key: "finance", label: "금융·커머스" },
  { key: "status", label: "상태·알림" },
  { key: "system", label: "시스템·개발" },
];

export interface CatalogIcon {
  /** 공식 컴포넌트명 (예: "HouseIcon"). import 문에 그대로 쓴다. */
  name: string;
  Icon: Icon;
  /** 영문+한글 검색어. */
  keywords: string[];
  category: IconCategory;
}

/** [name, Icon, keywords] 튜플로 카테고리별 정의를 압축한다. */
type Entry = [string, Icon, string[]];

function define(category: IconCategory, entries: Entry[]): CatalogIcon[] {
  return entries.map(([name, IconComponent, keywords]) => ({
    name,
    Icon: IconComponent,
    keywords,
    category,
  }));
}

export const ICON_CATALOG: CatalogIcon[] = [
  ...define("navigation", [
    ["HouseIcon", HouseIcon, ["home", "홈", "집"]],
    ["CompassIcon", CompassIcon, ["explore", "탐색", "나침반"]],
    ["MapPinIcon", MapPinIcon, ["location", "위치", "지도 핀"]],
    ["MapTrifoldIcon", MapTrifoldIcon, ["map", "지도"]],
    ["ListIcon", ListIcon, ["menu", "목록", "메뉴", "햄버거"]],
    ["FunnelIcon", FunnelIcon, ["filter", "필터", "깔때기"]],
    ["MagnifyingGlassIcon", MagnifyingGlassIcon, ["search", "검색", "돋보기"]],
    ["GlobeIcon", GlobeIcon, ["globe", "지구", "글로벌", "웹"]],
    ["ArrowLeftIcon", ArrowLeftIcon, ["back", "왼쪽", "뒤로"]],
    ["ArrowRightIcon", ArrowRightIcon, ["next", "오른쪽", "다음"]],
    ["ArrowUpIcon", ArrowUpIcon, ["up", "위"]],
    ["ArrowDownIcon", ArrowDownIcon, ["down", "아래"]],
    ["ArrowsClockwiseIcon", ArrowsClockwiseIcon, ["refresh", "새로고침", "동기화"]],
    ["ArrowSquareOutIcon", ArrowSquareOutIcon, ["external", "외부 링크", "새 창"]],
    ["CaretLeftIcon", CaretLeftIcon, ["chevron left", "이전"]],
    ["CaretRightIcon", CaretRightIcon, ["chevron right", "다음", "펼침"]],
    ["CaretUpIcon", CaretUpIcon, ["chevron up", "접기"]],
    ["CaretDownIcon", CaretDownIcon, ["chevron down", "펼치기", "드롭다운"]],
    ["CaretDoubleUpIcon", CaretDoubleUpIcon, ["double up", "맨 위"]],
    ["CaretDoubleDownIcon", CaretDoubleDownIcon, ["double down", "맨 아래", "더 보기"]],
    ["SignInIcon", SignInIcon, ["login", "로그인", "입장"]],
    ["SignOutIcon", SignOutIcon, ["logout", "로그아웃", "나가기"]],
    ["NavigationArrowIcon", NavigationArrowIcon, ["cursor", "내비게이션", "화살표"]],
    ["PathIcon", PathIcon, ["route", "경로", "라우트"]],
    ["SquaresFourIcon", SquaresFourIcon, ["grid", "그리드", "대시보드", "앱"]],
    ["DotsThreeIcon", DotsThreeIcon, ["more", "더보기", "가로 점"]],
    ["DotsThreeVerticalIcon", DotsThreeVerticalIcon, ["kebab", "케밥", "세로 점", "더보기"]],
    ["SidebarSimpleIcon", SidebarSimpleIcon, ["sidebar", "사이드바", "패널"]],
    ["XIcon", XIcon, ["close", "닫기", "엑스"]],
  ]),
  ...define("action", [
    ["PlusIcon", PlusIcon, ["add", "추가", "플러스"]],
    ["PlusCircleIcon", PlusCircleIcon, ["add circle", "추가", "새로 만들기"]],
    ["MinusIcon", MinusIcon, ["remove", "빼기", "마이너스"]],
    ["MinusCircleIcon", MinusCircleIcon, ["remove circle", "제거"]],
    ["PencilIcon", PencilIcon, ["edit", "편집", "연필", "수정"]],
    ["PencilSimpleIcon", PencilSimpleIcon, ["edit simple", "편집", "수정"]],
    ["TrashIcon", TrashIcon, ["delete", "삭제", "휴지통"]],
    ["TrashSimpleIcon", TrashSimpleIcon, ["delete simple", "삭제"]],
    ["CopyIcon", CopyIcon, ["copy", "복사"]],
    ["ClipboardIcon", ClipboardIcon, ["clipboard", "클립보드"]],
    ["ClipboardTextIcon", ClipboardTextIcon, ["clipboard text", "클립보드", "붙여넣기"]],
    ["CheckIcon", CheckIcon, ["check", "체크", "확인", "완료"]],
    ["CheckCircleIcon", CheckCircleIcon, ["check circle", "성공", "완료"]],
    ["XCircleIcon", XCircleIcon, ["x circle", "실패", "취소"]],
    ["DownloadSimpleIcon", DownloadSimpleIcon, ["download", "다운로드", "내려받기"]],
    ["UploadSimpleIcon", UploadSimpleIcon, ["upload", "업로드", "올리기"]],
    ["ExportIcon", ExportIcon, ["export", "내보내기"]],
    ["ShareNetworkIcon", ShareNetworkIcon, ["share", "공유"]],
    ["FloppyDiskIcon", FloppyDiskIcon, ["save", "저장", "디스크"]],
    ["ArrowCounterClockwiseIcon", ArrowCounterClockwiseIcon, ["undo", "되돌리기", "리셋"]],
    ["ArrowUUpLeftIcon", ArrowUUpLeftIcon, ["undo", "실행 취소"]],
    ["ArrowUUpRightIcon", ArrowUUpRightIcon, ["redo", "다시 실행"]],
    ["EyeIcon", EyeIcon, ["view", "보기", "조회", "눈"]],
    ["EyeSlashIcon", EyeSlashIcon, ["hide", "숨기기", "비공개"]],
    ["LockIcon", LockIcon, ["lock", "잠금", "보안"]],
    ["LockOpenIcon", LockOpenIcon, ["unlock", "잠금 해제"]],
    ["KeyIcon", KeyIcon, ["key", "키", "열쇠", "인증"]],
    ["PushPinIcon", PushPinIcon, ["pin", "고정", "핀"]],
    ["StarIcon", StarIcon, ["star", "별", "즐겨찾기", "북마크"]],
    ["HeartIcon", HeartIcon, ["heart", "하트", "좋아요", "찜"]],
    ["BookmarkSimpleIcon", BookmarkSimpleIcon, ["bookmark", "북마크", "책갈피"]],
    ["ThumbsUpIcon", ThumbsUpIcon, ["like", "좋아요", "추천"]],
    ["ThumbsDownIcon", ThumbsDownIcon, ["dislike", "싫어요", "비추천"]],
    ["DotsSixVerticalIcon", DotsSixVerticalIcon, ["drag handle", "드래그", "순서 변경"]],
  ]),
  ...define("object", [
    ["FileIcon", FileIcon, ["file", "파일"]],
    ["FileTextIcon", FileTextIcon, ["document", "문서", "텍스트 파일"]],
    ["FilePdfIcon", FilePdfIcon, ["pdf", "피디에프"]],
    ["FileCsvIcon", FileCsvIcon, ["csv", "엑셀", "표 파일"]],
    ["FileZipIcon", FileZipIcon, ["zip", "압축"]],
    ["FileCodeIcon", FileCodeIcon, ["code file", "코드 파일", "소스"]],
    ["FolderIcon", FolderIcon, ["folder", "폴더", "디렉터리"]],
    ["FolderOpenIcon", FolderOpenIcon, ["folder open", "열린 폴더"]],
    ["PaperclipIcon", PaperclipIcon, ["attachment", "첨부", "클립"]],
    ["ReceiptIcon", ReceiptIcon, ["receipt", "영수증"]],
    ["BookIcon", BookIcon, ["book", "책"]],
    ["BookOpenIcon", BookOpenIcon, ["book open", "펼친 책", "읽기", "매뉴얼"]],
    ["NotebookIcon", NotebookIcon, ["notebook", "노트", "수첩"]],
    ["NoteIcon", NoteIcon, ["note", "메모"]],
    ["ArchiveIcon", ArchiveIcon, ["archive", "보관", "아카이브"]],
    ["PackageIcon", PackageIcon, ["package", "패키지", "상자", "배송"]],
    ["CubeIcon", CubeIcon, ["cube", "큐브", "3d", "모듈"]],
    ["BriefcaseIcon", BriefcaseIcon, ["briefcase", "서류가방", "업무", "비즈니스"]],
    ["BuildingsIcon", BuildingsIcon, ["company", "회사", "건물", "기업"]],
    ["CalendarIcon", CalendarIcon, ["calendar", "달력", "일정"]],
    ["CalendarBlankIcon", CalendarBlankIcon, ["calendar blank", "빈 달력", "날짜"]],
    ["ClockIcon", ClockIcon, ["clock", "시계", "시간"]],
    ["TimerIcon", TimerIcon, ["timer", "타이머", "스톱워치"]],
    ["AlarmIcon", AlarmIcon, ["alarm", "알람"]],
    ["HourglassIcon", HourglassIcon, ["hourglass", "모래시계", "대기"]],
    ["ImageIcon", ImageIcon, ["image", "이미지", "사진", "그림"]],
    ["CameraIcon", CameraIcon, ["camera", "카메라", "촬영"]],
    ["PrinterIcon", PrinterIcon, ["print", "프린터", "인쇄"]],
    ["DesktopIcon", DesktopIcon, ["desktop", "데스크톱", "모니터", "피시"]],
    ["DeviceMobileIcon", DeviceMobileIcon, ["mobile", "모바일", "휴대폰", "스마트폰"]],
    ["LaptopIcon", LaptopIcon, ["laptop", "노트북"]],
  ]),
  ...define("communication", [
    ["ChatCircleIcon", ChatCircleIcon, ["chat", "채팅", "대화", "말풍선"]],
    ["ChatTextIcon", ChatTextIcon, ["chat text", "메시지", "댓글"]],
    ["ChatsIcon", ChatsIcon, ["chats", "대화 목록", "채팅방"]],
    ["EnvelopeIcon", EnvelopeIcon, ["mail", "메일", "편지", "이메일"]],
    ["EnvelopeSimpleIcon", EnvelopeSimpleIcon, ["mail simple", "메일"]],
    ["BellIcon", BellIcon, ["notification", "알림", "종"]],
    ["BellRingingIcon", BellRingingIcon, ["bell ringing", "알림 울림", "신규 알림"]],
    ["BellSlashIcon", BellSlashIcon, ["mute", "알림 끄기", "음소거"]],
    ["MegaphoneIcon", MegaphoneIcon, ["announcement", "공지", "확성기", "홍보"]],
    ["PhoneIcon", PhoneIcon, ["phone", "전화"]],
    ["PhoneCallIcon", PhoneCallIcon, ["call", "통화"]],
    ["PaperPlaneTiltIcon", PaperPlaneTiltIcon, ["send", "보내기", "전송", "종이비행기"]],
    ["PaperPlaneRightIcon", PaperPlaneRightIcon, ["send right", "전송"]],
    ["AtIcon", AtIcon, ["mention", "멘션", "골뱅이"]],
    ["LinkIcon", LinkIcon, ["link", "링크", "연결"]],
    ["LinkBreakIcon", LinkBreakIcon, ["unlink", "링크 해제", "연결 끊김"]],
    ["QuotesIcon", QuotesIcon, ["quote", "인용", "따옴표"]],
    ["TranslateIcon", TranslateIcon, ["translate", "번역", "다국어"]],
    ["UserIcon", UserIcon, ["user", "사용자", "회원", "프로필"]],
    ["UserCircleIcon", UserCircleIcon, ["user circle", "프로필", "아바타"]],
    ["UserPlusIcon", UserPlusIcon, ["invite", "사용자 추가", "초대"]],
    ["UsersIcon", UsersIcon, ["team", "팀", "그룹", "사용자들"]],
    ["UsersThreeIcon", UsersThreeIcon, ["community", "커뮤니티", "조직"]],
    ["AddressBookIcon", AddressBookIcon, ["contacts", "주소록", "연락처"]],
    ["IdentificationCardIcon", IdentificationCardIcon, ["id card", "신분증", "사원증"]],
  ]),
  ...define("media", [
    ["PlayIcon", PlayIcon, ["play", "재생"]],
    ["PauseIcon", PauseIcon, ["pause", "일시정지"]],
    ["StopIcon", StopIcon, ["stop", "정지"]],
    ["SkipBackIcon", SkipBackIcon, ["previous", "이전 곡"]],
    ["SkipForwardIcon", SkipForwardIcon, ["next", "다음 곡"]],
    ["RewindIcon", RewindIcon, ["rewind", "되감기"]],
    ["FastForwardIcon", FastForwardIcon, ["fast forward", "빨리 감기"]],
    ["SpeakerHighIcon", SpeakerHighIcon, ["volume", "볼륨", "스피커"]],
    ["SpeakerLowIcon", SpeakerLowIcon, ["volume low", "작은 소리"]],
    ["SpeakerSlashIcon", SpeakerSlashIcon, ["mute", "음소거"]],
    ["MicrophoneIcon", MicrophoneIcon, ["microphone", "마이크", "녹음"]],
    ["MicrophoneSlashIcon", MicrophoneSlashIcon, ["mic off", "마이크 끄기"]],
    ["MusicNoteIcon", MusicNoteIcon, ["music", "음악", "음표"]],
    ["MusicNotesIcon", MusicNotesIcon, ["music notes", "음악", "플레이리스트"]],
    ["PlaylistIcon", PlaylistIcon, ["playlist", "재생목록"]],
    ["HeadphonesIcon", HeadphonesIcon, ["headphones", "헤드폰", "청취"]],
    ["VideoIcon", VideoIcon, ["video", "비디오", "동영상"]],
    ["VideoCameraIcon", VideoCameraIcon, ["video camera", "화상", "캠"]],
    ["FilmSlateIcon", FilmSlateIcon, ["film", "영화", "클래퍼"]],
    ["TelevisionIcon", TelevisionIcon, ["tv", "티비", "방송"]],
    ["BroadcastIcon", BroadcastIcon, ["broadcast", "방송", "라이브", "송출"]],
    ["ScreencastIcon", ScreencastIcon, ["screencast", "화면 공유", "미러링"]],
    ["WaveformIcon", WaveformIcon, ["waveform", "파형", "오디오"]],
  ]),
  ...define("chart", [
    ["ChartBarIcon", ChartBarIcon, ["bar chart", "막대 차트", "그래프"]],
    ["ChartBarHorizontalIcon", ChartBarHorizontalIcon, ["horizontal bar", "가로 막대"]],
    ["ChartLineIcon", ChartLineIcon, ["line chart", "선 차트", "추이"]],
    ["ChartLineUpIcon", ChartLineUpIcon, ["line up", "상승 추세", "성장"]],
    ["ChartLineDownIcon", ChartLineDownIcon, ["line down", "하락 추세"]],
    ["ChartPieIcon", ChartPieIcon, ["pie chart", "파이 차트", "비중"]],
    ["ChartPieSliceIcon", ChartPieSliceIcon, ["pie slice", "파이 조각"]],
    ["ChartDonutIcon", ChartDonutIcon, ["donut chart", "도넛 차트"]],
    ["ChartScatterIcon", ChartScatterIcon, ["scatter", "산점도"]],
    ["TrendUpIcon", TrendUpIcon, ["trend up", "상승", "오름세"]],
    ["TrendDownIcon", TrendDownIcon, ["trend down", "하락", "내림세"]],
    ["TableIcon", TableIcon, ["table", "테이블", "표"]],
    ["RowsIcon", RowsIcon, ["rows", "행", "로우"]],
    ["ColumnsIcon", ColumnsIcon, ["columns", "열", "컬럼"]],
    ["DatabaseIcon", DatabaseIcon, ["database", "데이터베이스", "디비"]],
    ["HardDriveIcon", HardDriveIcon, ["storage", "저장소", "하드"]],
    ["HardDrivesIcon", HardDrivesIcon, ["servers", "서버", "스토리지"]],
    ["GaugeIcon", GaugeIcon, ["gauge", "게이지", "속도계", "성능"]],
    ["TargetIcon", TargetIcon, ["target", "타깃", "목표", "과녁"]],
    ["PercentIcon", PercentIcon, ["percent", "퍼센트", "비율"]],
    ["SigmaIcon", SigmaIcon, ["sum", "시그마", "합계"]],
    ["GraphIcon", GraphIcon, ["graph", "그래프", "네트워크", "노드"]],
    ["TreeStructureIcon", TreeStructureIcon, ["tree", "트리", "계층", "조직도"]],
    ["BinocularsIcon", BinocularsIcon, ["observe", "관찰", "쌍안경", "모니터링"]],
    ["CrosshairIcon", CrosshairIcon, ["crosshair", "조준", "정밀"]],
  ]),
  ...define("finance", [
    ["MoneyIcon", MoneyIcon, ["money", "돈", "지폐", "현금"]],
    ["CurrencyKrwIcon", CurrencyKrwIcon, ["krw", "원화", "원"]],
    ["CurrencyDollarIcon", CurrencyDollarIcon, ["dollar", "달러"]],
    ["CurrencyEurIcon", CurrencyEurIcon, ["euro", "유로"]],
    ["CurrencyBtcIcon", CurrencyBtcIcon, ["bitcoin", "비트코인", "코인"]],
    ["CurrencyCircleDollarIcon", CurrencyCircleDollarIcon, ["price", "가격", "금액"]],
    ["CoinsIcon", CoinsIcon, ["coins", "동전", "포인트"]],
    ["CreditCardIcon", CreditCardIcon, ["credit card", "카드", "결제"]],
    ["BankIcon", BankIcon, ["bank", "은행", "금융"]],
    ["WalletIcon", WalletIcon, ["wallet", "지갑"]],
    ["PiggyBankIcon", PiggyBankIcon, ["savings", "저축", "저금통"]],
    ["CalculatorIcon", CalculatorIcon, ["calculator", "계산기"]],
    ["ScalesIcon", ScalesIcon, ["scales", "저울", "형평", "법"]],
    ["HandshakeIcon", HandshakeIcon, ["deal", "계약", "악수", "파트너"]],
    ["ShoppingCartIcon", ShoppingCartIcon, ["cart", "장바구니", "카트"]],
    ["ShoppingBagIcon", ShoppingBagIcon, ["shopping bag", "쇼핑백", "구매"]],
    ["StorefrontIcon", StorefrontIcon, ["store", "상점", "스토어", "매장"]],
    ["TagIcon", TagIcon, ["tag", "태그", "라벨", "가격표"]],
    ["TicketIcon", TicketIcon, ["ticket", "티켓", "쿠폰"]],
    ["GiftIcon", GiftIcon, ["gift", "선물", "이벤트"]],
    ["TruckIcon", TruckIcon, ["delivery", "배송", "트럭", "물류"]],
    ["BarcodeIcon", BarcodeIcon, ["barcode", "바코드"]],
    ["QrCodeIcon", QrCodeIcon, ["qr", "큐알", "큐알코드"]],
  ]),
  ...define("status", [
    ["InfoIcon", InfoIcon, ["info", "정보", "안내"]],
    ["QuestionIcon", QuestionIcon, ["question", "질문", "도움말", "물음표"]],
    ["WarningIcon", WarningIcon, ["warning", "경고", "주의"]],
    ["WarningCircleIcon", WarningCircleIcon, ["warning circle", "경고", "오류"]],
    ["WarningOctagonIcon", WarningOctagonIcon, ["stop warning", "심각", "차단"]],
    ["CheckSquareIcon", CheckSquareIcon, ["checkbox", "체크박스", "선택"]],
    ["XSquareIcon", XSquareIcon, ["x square", "선택 해제"]],
    ["ProhibitIcon", ProhibitIcon, ["prohibit", "금지", "차단"]],
    ["CircleNotchIcon", CircleNotchIcon, ["loading", "로딩", "스피너"]],
    ["SpinnerIcon", SpinnerIcon, ["spinner", "로딩", "처리 중"]],
    ["SpinnerGapIcon", SpinnerGapIcon, ["spinner gap", "로딩"]],
    ["PulseIcon", PulseIcon, ["pulse", "활동", "모니터링", "맥박"]],
    ["HeartbeatIcon", HeartbeatIcon, ["heartbeat", "헬스체크", "심박"]],
    ["ShieldIcon", ShieldIcon, ["shield", "방패", "보호"]],
    ["ShieldCheckIcon", ShieldCheckIcon, ["shield check", "보안 통과", "안전"]],
    ["ShieldWarningIcon", ShieldWarningIcon, ["shield warning", "보안 경고", "취약점"]],
    ["SealCheckIcon", SealCheckIcon, ["verified", "인증", "검증 완료"]],
    ["SealWarningIcon", SealWarningIcon, ["seal warning", "인증 경고"]],
    ["FingerprintIcon", FingerprintIcon, ["fingerprint", "지문", "생체 인증"]],
    ["BugIcon", BugIcon, ["bug", "버그", "결함"]],
    ["FireIcon", FireIcon, ["fire", "불", "인기", "핫"]],
    ["LightningIcon", LightningIcon, ["lightning", "번개", "빠름", "즉시"]],
    ["CloudCheckIcon", CloudCheckIcon, ["cloud ok", "클라우드 정상", "동기화 완료"]],
    ["CloudArrowUpIcon", CloudArrowUpIcon, ["cloud upload", "클라우드 업로드"]],
    ["CloudArrowDownIcon", CloudArrowDownIcon, ["cloud download", "클라우드 다운로드"]],
    ["WifiHighIcon", WifiHighIcon, ["wifi", "와이파이", "온라인"]],
    ["WifiSlashIcon", WifiSlashIcon, ["offline", "오프라인", "연결 끊김"]],
  ]),
  ...define("system", [
    ["GearIcon", GearIcon, ["settings", "설정", "톱니"]],
    ["GearSixIcon", GearSixIcon, ["settings six", "환경설정"]],
    ["SlidersIcon", SlidersIcon, ["sliders", "조절", "필터 설정"]],
    ["SlidersHorizontalIcon", SlidersHorizontalIcon, ["sliders horizontal", "옵션"]],
    ["FadersIcon", FadersIcon, ["faders", "페이더", "믹서", "세부 조정"]],
    ["WrenchIcon", WrenchIcon, ["wrench", "렌치", "수리", "도구"]],
    ["ToolboxIcon", ToolboxIcon, ["toolbox", "공구함", "도구 모음"]],
    ["TerminalIcon", TerminalIcon, ["terminal", "터미널", "셸"]],
    ["TerminalWindowIcon", TerminalWindowIcon, ["terminal window", "콘솔 창"]],
    ["CodeIcon", CodeIcon, ["code", "코드", "개발"]],
    ["CodeBlockIcon", CodeBlockIcon, ["code block", "코드 블록"]],
    ["GitBranchIcon", GitBranchIcon, ["git branch", "브랜치"]],
    ["GitCommitIcon", GitCommitIcon, ["git commit", "커밋"]],
    ["GitMergeIcon", GitMergeIcon, ["git merge", "머지", "병합"]],
    ["GitPullRequestIcon", GitPullRequestIcon, ["pull request", "피알", "머지 요청"]],
    ["GithubLogoIcon", GithubLogoIcon, ["github", "깃허브"]],
    ["GitlabLogoIcon", GitlabLogoIcon, ["gitlab", "깃랩"]],
    ["CpuIcon", CpuIcon, ["cpu", "씨피유", "프로세서"]],
    ["CircuitryIcon", CircuitryIcon, ["circuit", "회로", "하드웨어"]],
    ["RobotIcon", RobotIcon, ["robot", "로봇", "봇", "자동화"]],
    ["BrainIcon", BrainIcon, ["brain", "브레인", "에이아이", "지능"]],
    ["SparkleIcon", SparkleIcon, ["sparkle", "반짝", "에이아이", "생성형"]],
    ["MagicWandIcon", MagicWandIcon, ["magic", "마법봉", "자동 생성"]],
    ["PlugIcon", PlugIcon, ["plug", "플러그", "연결"]],
    ["PlugsIcon", PlugsIcon, ["plugs", "플러그", "통합"]],
    ["PlugsConnectedIcon", PlugsConnectedIcon, ["connected", "연결됨", "연동"]],
    ["PowerIcon", PowerIcon, ["power", "전원", "켜기 끄기"]],
    ["StackIcon", StackIcon, ["stack", "스택", "레이어"]],
    ["StackSimpleIcon", StackSimpleIcon, ["stack simple", "계층"]],
    ["CommandIcon", CommandIcon, ["command", "커맨드", "단축키"]],
    ["KeyboardIcon", KeyboardIcon, ["keyboard", "키보드", "입력"]],
    ["BrowserIcon", BrowserIcon, ["browser", "브라우저", "웹 창"]],
    ["BrowsersIcon", BrowsersIcon, ["browsers", "브라우저 여러 개", "탭"]],
    ["LightbulbIcon", LightbulbIcon, ["idea", "아이디어", "전구", "팁"]],
    ["SunIcon", SunIcon, ["light mode", "라이트 모드", "해"]],
    ["MoonIcon", MoonIcon, ["dark mode", "다크 모드", "달"]],
    ["PaletteIcon", PaletteIcon, ["palette", "팔레트", "색상", "테마"]],
    ["PaintBrushIcon", PaintBrushIcon, ["paint", "붓", "디자인"]],
    ["EyedropperIcon", EyedropperIcon, ["eyedropper", "스포이드", "색 추출"]],
    ["SwatchesIcon", SwatchesIcon, ["swatches", "스와치", "색 견본"]],
  ]),
];

export function searchIcons(query: string, category?: IconCategory): CatalogIcon[] {
  const q = query.trim().toLowerCase();
  return ICON_CATALOG.filter((icon) => {
    if (category && icon.category !== category) return false;
    if (!q) return true;
    return (
      icon.name.toLowerCase().includes(q) ||
      icon.keywords.some((keyword) => keyword.toLowerCase().includes(q))
    );
  });
}
