import type { ThemeTokens } from "@/themes";

/** /tokens 페이지에서 각 시맨틱 토큰의 용도를 한 줄로 설명한다. */
export const TOKEN_DESCRIPTIONS: Record<keyof ThemeTokens, string> = {
  background: "페이지 최상위 배경",
  foreground: "기본 본문 텍스트",
  card: "카드·패널 배경",
  "card-foreground": "카드 위 텍스트",
  popover: "팝오버·드롭다운·툴팁 배경",
  "popover-foreground": "팝오버 위 텍스트",
  primary: "주요 액션(버튼·강조 요소) 배경",
  "primary-foreground": "primary 위 텍스트",
  secondary: "보조 액션 배경",
  "secondary-foreground": "secondary 위 텍스트",
  muted: "톤 다운된 배경(구분 영역)",
  "muted-foreground": "설명·보조 텍스트",
  accent: "hover/선택 상태 강조 배경",
  "accent-foreground": "accent 위 텍스트",
  destructive: "삭제·위험 액션",
  success: "성공·완료 상태",
  warning: "경고 상태",
  gain: "한국식 등락 — 이익/상승(빨강)",
  loss: "한국식 등락 — 손실/하락(파랑)",
  border: "테두리 선",
  input: "입력 필드 테두리",
  ring: "포커스 링",
  "chart-1": "차트 시리즈 1",
  "chart-2": "차트 시리즈 2",
  "chart-3": "차트 시리즈 3",
  "chart-4": "차트 시리즈 4",
  "chart-5": "차트 시리즈 5",
  bulb: "브랜드 확장(opt-in) — 시그니처 포인트 컬러",
  shell: "브랜드 확장(opt-in) — 셸 상판 배경",
  shellForeground: "브랜드 확장(opt-in) — 셸 상판 위 텍스트",
  shellMuted: "브랜드 확장(opt-in) — 셸 상판 보조 텍스트",
};
