import type { ComponentEntry } from "@/lib/showcase/types"

/**
 * 쇼케이스 레지스트리 — 단일 진실원천.
 * components/ui/ 의 shadcn 컴포넌트 전체(60종) + components/ 바로 아래 커스텀
 * 패턴(수동 등록, 현재 4종: screen-help-dialog·format-biz-no·badge-extended·
 * tooltip-icon-button)을 카테고리별로 등록한다.
 * status: "done" = components/demos/<slug>.demo.tsx 존재, 그 외 값 = 데모 준비 전.
 *
 * 여기에 항목을 추가/수정하면 /components 인덱스와 /components/<slug> 상세
 * 페이지에 자동 반영된다. 새 데모를 추가하면 lib/showcase/demo-loaders.ts 에
 * 로더를 등록하고 이 파일의 status 를 "done"으로 바꾼다.
 */
export const COMPONENT_REGISTRY: ComponentEntry[] = [
  // ── Form ──────────────────────────────────────────────
  {
    slug: "button",
    title: "Button",
    category: "form",
    layer: "primitive",
    description: "클릭 가능한 기본 액션 트리거. variant·size 조합을 제공합니다.",
    status: "done",
  },
  {
    slug: "button-group",
    title: "Button Group",
    category: "form",
    layer: "primitive",
    description: "버튼을 시각적으로 묶어 하나의 액션 세트로 보여줍니다.",
    status: "done",
  },
  {
    slug: "calendar",
    title: "Calendar",
    category: "form",
    layer: "primitive",
    description: "단일/범위 날짜 선택을 지원하는 달력 위젯입니다.",
    status: "done",
  },
  {
    slug: "checkbox",
    title: "Checkbox",
    category: "form",
    layer: "primitive",
    description: "다중 선택이 가능한 체크박스 입력입니다.",
    status: "done",
  },
  {
    slug: "combobox",
    title: "Combobox",
    category: "form",
    layer: "primitive",
    description: "검색 가능한 목록에서 값을 선택하는 콤보박스입니다.",
    status: "done",
  },
  {
    slug: "field",
    title: "Field",
    category: "form",
    layer: "primitive",
    description: "레이블·설명·에러 메시지를 갖춘 폼 필드 레이아웃 프리미티브입니다.",
    status: "done",
  },
  {
    slug: "input",
    title: "Input",
    category: "form",
    layer: "primitive",
    description: "한 줄 텍스트를 입력받는 기본 텍스트 필드입니다.",
    status: "done",
  },
  {
    slug: "input-group",
    title: "Input Group",
    category: "form",
    layer: "primitive",
    description: "아이콘·버튼·텍스트 애드온을 입력 필드에 붙일 때 사용합니다.",
    status: "done",
  },
  {
    slug: "input-otp",
    title: "Input OTP",
    category: "form",
    layer: "primitive",
    description: "일회용 인증 코드처럼 자릿수가 고정된 입력에 사용합니다.",
    status: "done",
  },
  {
    slug: "label",
    title: "Label",
    category: "form",
    layer: "primitive",
    description: "폼 컨트롤에 접근성 있게 연결되는 레이블입니다.",
    status: "done",
  },
  {
    slug: "native-select",
    title: "Native Select",
    category: "form",
    layer: "primitive",
    description: "브라우저 기본 select 엘리먼트를 스타일링한 셀렉트입니다.",
    status: "done",
  },
  {
    slug: "radio-group",
    title: "Radio Group",
    category: "form",
    layer: "primitive",
    description: "여러 옵션 중 하나만 선택하는 라디오 버튼 그룹입니다.",
    status: "done",
  },
  {
    slug: "select",
    title: "Select",
    category: "form",
    layer: "primitive",
    description: "커스텀 드롭다운으로 하나의 값을 선택합니다.",
    status: "done",
  },
  {
    slug: "slider",
    title: "Slider",
    category: "form",
    layer: "primitive",
    description: "범위 내 숫자 값을 드래그로 조절하는 슬라이더입니다.",
    status: "done",
  },
  {
    slug: "switch",
    title: "Switch",
    category: "form",
    layer: "primitive",
    description: "켜짐/꺼짐 상태를 전환하는 토글 스위치입니다.",
    status: "done",
  },
  {
    slug: "textarea",
    title: "Textarea",
    category: "form",
    layer: "primitive",
    description: "여러 줄 텍스트를 입력받는 필드입니다.",
    status: "done",
  },
  {
    slug: "toggle",
    title: "Toggle",
    category: "form",
    layer: "primitive",
    description: "눌림/눌리지 않음 두 상태를 갖는 단일 토글 버튼입니다.",
    status: "done",
  },
  {
    slug: "toggle-group",
    title: "Toggle Group",
    category: "form",
    layer: "primitive",
    description: "여러 토글 버튼을 묶어 단일/다중 선택을 지원합니다.",
    status: "done",
  },
  {
    slug: "tooltip-icon-button",
    title: "Tooltip Icon Button",
    category: "form",
    layer: "composition",
    description: "아이콘 전용 버튼에 Tooltip과 aria-label을 강제로 붙여주는 규칙강제 컴포넌트입니다(#21).",
    status: "done",
  },

  // ── Overlay ───────────────────────────────────────────
  {
    slug: "dialog",
    title: "Dialog",
    category: "overlay",
    layer: "primitive",
    description: "화면을 덮는 모달 대화상자입니다.",
    status: "done",
  },
  {
    slug: "alert-dialog",
    title: "Alert Dialog",
    category: "overlay",
    layer: "primitive",
    description: "확인이 필요한 파괴적 액션 전에 띄우는 모달입니다.",
    status: "done",
  },
  {
    slug: "sheet",
    title: "Sheet",
    category: "overlay",
    layer: "primitive",
    description: "화면 가장자리에서 슬라이드로 열리는 패널입니다.",
    status: "done",
  },
  {
    slug: "drawer",
    title: "Drawer",
    category: "overlay",
    layer: "primitive",
    description: "모바일 친화적인 하단 슬라이드 시트입니다.",
    status: "done",
  },
  {
    slug: "popover",
    title: "Popover",
    category: "overlay",
    layer: "primitive",
    description: "트리거 요소 주변에 뜨는 자유 형식 콘텐츠 오버레이입니다.",
    status: "done",
  },
  {
    slug: "tooltip",
    title: "Tooltip",
    category: "overlay",
    layer: "primitive",
    description: "호버·포커스 시 짧은 설명을 보여줍니다.",
    status: "done",
  },
  {
    slug: "hover-card",
    title: "Hover Card",
    category: "overlay",
    layer: "primitive",
    description: "호버 시 미리보기 카드를 보여줍니다.",
    status: "done",
  },
  {
    slug: "context-menu",
    title: "Context Menu",
    category: "overlay",
    layer: "primitive",
    description: "우클릭으로 여는 컨텍스트 메뉴입니다.",
    status: "done",
  },
  {
    slug: "dropdown-menu",
    title: "Dropdown Menu",
    category: "overlay",
    layer: "primitive",
    description: "트리거 클릭으로 여는 드롭다운 메뉴입니다.",
    status: "done",
  },
  {
    slug: "kebab-menu",
    title: "Kebab Menu",
    category: "overlay",
    layer: "composition",
    description: "세로 점 3개(⋮) 아이콘 버튼을 누르면 액션 드롭다운이 열리는 케밥 메뉴입니다. items 배열 하나로 선언하며 트리거의 aria-label을 label prop으로 강제합니다.",
    status: "done",
  },
  {
    slug: "menubar",
    title: "Menubar",
    category: "overlay",
    layer: "primitive",
    description: "데스크톱 앱 스타일의 상단 메뉴 바입니다.",
    status: "done",
  },
  {
    slug: "command",
    title: "Command",
    category: "overlay",
    layer: "primitive",
    description: "검색 가능한 커맨드 팔레트입니다.",
    status: "done",
  },
  {
    slug: "sonner",
    title: "Sonner (Toast)",
    category: "overlay",
    layer: "primitive",
    description: "일시적으로 뜨는 토스트 알림입니다.",
    status: "done",
  },

  // ── Layout ────────────────────────────────────────────
  {
    slug: "card",
    title: "Card",
    category: "layout",
    layer: "primitive",
    description: "콘텐츠를 묶는 기본 카드 컨테이너입니다.",
    status: "done",
  },
  {
    slug: "separator",
    title: "Separator",
    category: "layout",
    layer: "primitive",
    description: "콘텐츠 사이를 구분하는 선입니다.",
    status: "done",
  },
  {
    slug: "aspect-ratio",
    title: "Aspect Ratio",
    category: "layout",
    layer: "primitive",
    description: "자식 요소의 가로세로 비율을 고정합니다.",
    status: "done",
  },
  {
    slug: "resizable",
    title: "Resizable",
    category: "layout",
    layer: "primitive",
    description: "드래그로 크기를 조절하는 패널 레이아웃입니다.",
    status: "done",
  },
  {
    slug: "scroll-area",
    title: "Scroll Area",
    category: "layout",
    layer: "primitive",
    description: "커스텀 스크롤바를 가진 스크롤 영역입니다.",
    status: "done",
  },
  {
    slug: "sidebar",
    title: "Sidebar",
    category: "layout",
    layer: "primitive",
    description: "접고 펼 수 있는 앱 사이드바 프리미티브입니다.",
    status: "done",
  },
  {
    slug: "tabs",
    title: "Tabs",
    category: "layout",
    layer: "primitive",
    description: "탭으로 전환되는 콘텐츠 패널입니다.",
    status: "done",
  },
  {
    slug: "accordion",
    title: "Accordion",
    category: "layout",
    layer: "primitive",
    description: "펼치고 접을 수 있는 콘텐츠 섹션입니다.",
    status: "done",
  },
  {
    slug: "collapsible",
    title: "Collapsible",
    category: "layout",
    layer: "primitive",
    description: "단일 콘텐츠 블록을 펼치고 접습니다.",
    status: "done",
  },

  // ── Data ──────────────────────────────────────────────
  {
    slug: "table",
    title: "Table",
    category: "data",
    layer: "primitive",
    description: "행/열 구조의 데이터를 표시하는 테이블입니다.",
    status: "done",
  },
  {
    slug: "badge",
    title: "Badge",
    category: "data",
    layer: "primitive",
    description: "상태·카운트를 나타내는 작은 라벨입니다.",
    status: "done",
  },
  {
    slug: "badge-extended",
    title: "Badge Extended",
    category: "data",
    layer: "composition",
    description: "shadcn Badge에 success/warning/danger 시맨틱 상태 variant를 추가한 규칙강제 컴포넌트입니다(#21).",
    status: "done",
  },
  {
    slug: "avatar",
    title: "Avatar",
    category: "data",
    layer: "primitive",
    description: "사용자 프로필 이미지 또는 이니셜을 보여줍니다.",
    status: "done",
  },
  {
    slug: "skeleton",
    title: "Skeleton",
    category: "data",
    layer: "primitive",
    description: "로딩 중임을 나타내는 플레이스홀더 블록입니다.",
    status: "done",
  },
  {
    slug: "progress",
    title: "Progress",
    category: "data",
    layer: "primitive",
    description: "작업 진행률을 보여주는 바입니다.",
    status: "done",
  },
  {
    slug: "chart",
    title: "Chart",
    category: "data",
    layer: "primitive",
    description: "recharts 기반 차트 래퍼 컴포넌트입니다.",
    status: "done",
  },
  {
    slug: "empty",
    title: "Empty",
    category: "data",
    layer: "primitive",
    description: "데이터가 없을 때 보여주는 빈 상태 화면입니다.",
    status: "done",
  },
  {
    slug: "item",
    title: "Item",
    category: "data",
    layer: "primitive",
    description: "아이콘·텍스트·액션을 갖춘 리스트 항목 레이아웃입니다.",
    status: "done",
  },
  {
    slug: "kbd",
    title: "Kbd",
    category: "data",
    layer: "primitive",
    description: "키보드 단축키를 표시하는 인라인 요소입니다.",
    status: "done",
  },
  {
    slug: "marker",
    title: "Marker",
    category: "data",
    layer: "primitive",
    description: "타임라인·리스트에서 항목을 표시하는 마커입니다.",
    status: "done",
  },
  {
    slug: "spinner",
    title: "Spinner",
    category: "data",
    layer: "primitive",
    description: "비동기 작업 중임을 나타내는 회전 인디케이터입니다.",
    status: "done",
  },
  {
    slug: "alert",
    title: "Alert",
    category: "data",
    layer: "primitive",
    description: "정보·경고·오류 메시지를 강조해서 보여줍니다.",
    status: "done",
  },
  {
    slug: "carousel",
    title: "Carousel",
    category: "data",
    layer: "primitive",
    description: "여러 항목을 슬라이드로 넘겨보는 캐러셀입니다.",
    status: "done",
  },
  {
    slug: "pagination",
    title: "Pagination",
    category: "data",
    layer: "primitive",
    description: "페이지 단위로 나뉜 콘텐츠를 탐색합니다.",
    status: "done",
  },
  {
    slug: "breadcrumb",
    title: "Breadcrumb",
    category: "data",
    layer: "primitive",
    description: "현재 위치까지의 경로를 보여주는 내비게이션입니다.",
    status: "done",
  },
  {
    slug: "navigation-menu",
    title: "Navigation Menu",
    category: "data",
    layer: "primitive",
    description: "드롭다운을 포함한 상단 내비게이션 메뉴입니다.",
    status: "done",
  },
  {
    slug: "table-sortable",
    title: "Table Sortable",
    category: "data",
    layer: "composition",
    description:
      "고정 헤더+스크롤 바디, 컬럼 정렬, 행 드래그 재정렬, 컬럼 표시/숨김 토글을 갖춘 제네릭 데이터 그리드입니다(tossinvest 이식, #24).",
    status: "done",
  },
  {
    slug: "table-toggle",
    title: "Table Toggle",
    category: "data",
    layer: "composition",
    description:
      "행마다 on/off Switch가 붙은 관리자용 테이블입니다. 낙관적 업데이트, 실패 롤백+사유 표시, 행 단위 진행 상태, data 재조정을 지원합니다(#69).",
    status: "done",
  },

  // ── Chat ──────────────────────────────────────────────
  {
    slug: "message",
    title: "Message",
    category: "chat",
    layer: "primitive",
    description: "채팅 메시지 한 건을 표현하는 컴포넌트입니다.",
    status: "done",
  },
  {
    slug: "message-scroller",
    title: "Message Scroller",
    category: "chat",
    layer: "primitive",
    description: "새 메시지에 자동으로 스크롤을 따라가는 컨테이너입니다.",
    status: "done",
  },
  {
    slug: "bubble",
    title: "Bubble",
    category: "chat",
    layer: "primitive",
    description: "발신자에 따라 스타일이 달라지는 채팅 말풍선입니다.",
    status: "done",
  },
  {
    slug: "attachment",
    title: "Attachment",
    category: "chat",
    layer: "primitive",
    description: "채팅에 첨부된 파일을 미리 보여줍니다.",
    status: "done",
  },
  {
    slug: "direction",
    title: "Direction",
    category: "chat",
    layer: "primitive",
    description: "발신 방향(내가 보냄/상대가 보냄)에 따라 정렬을 바꿉니다.",
    status: "done",
  },

  // ── Bizinfo (프로젝트 확장) ───────────────────────────
  {
    slug: "screen-help-dialog",
    title: "Screen Help Dialog",
    category: "bizinfo",
    layer: "composition",
    description: "화면 제목 옆 (?) 버튼으로 여는 화면 매뉴얼 다이얼로그입니다(bizinfo 이식, #8).",
    status: "done",
  },
  {
    slug: "region-map",
    title: "Region Map",
    category: "bizinfo",
    layer: "composition",
    description:
      "한국 시/도 분포 지도 — 지리 지도(hover 3D 돌출·리치 툴팁) ↔ 타일 카토그램 토글입니다(bizinfo 이식, #56).",
    status: "done",
  },
  {
    slug: "format-biz-no",
    title: "formatBizNo",
    category: "bizinfo",
    layer: "composition",
    description: "사업자등록번호를 000-00-00000 형태로 포맷하는 화면 표시용 유틸입니다(bizinfo 이식, #8).",
    status: "done",
  },

  // ── Finance (프로젝트 확장) ───────────────────────────
  {
    slug: "rate-color",
    title: "rateColor / rateText",
    category: "finance",
    layer: "composition",
    description:
      "한국식 등락 색(이익=빨강/손실=파랑) 클래스와 부호 포함 등락률 텍스트를 만드는 유틸입니다(tossinvest 이식, #18).",
    status: "done",
  },
  {
    slug: "format-won",
    title: "formatWon",
    category: "finance",
    layer: "composition",
    description: "원화 금액을 억/조 단위로 축약해 표시하는 유틸입니다(news FlowPanel eok() 이식, #18).",
    status: "done",
  },
  {
    slug: "date-picker",
    title: "Date Picker",
    category: "form",
    layer: "composition",
    description: "calendar+popover 조합 단일 날짜 선택기입니다.",
    status: "done",
  },
  {
    slug: "date-range-picker",
    title: "Date Range Picker",
    category: "form",
    layer: "composition",
    description: "2달 캘린더로 from~to 기간을 선택하는 범위 선택기입니다.",
    status: "done",
  },
  {
    slug: "multi-select",
    title: "Multi Select",
    category: "form",
    layer: "composition",
    description: "command 팝오버 다중 선택 + 선택 항목 칩(제거) 표시 컴포넌트입니다.",
    status: "done",
  },
  {
    slug: "password-input",
    title: "Password Input",
    category: "form",
    layer: "composition",
    description: "눈 아이콘 토글로 표시/숨김하는 비밀번호 입력입니다.",
    status: "done",
  },
  {
    slug: "number-input",
    title: "Number Input",
    category: "form",
    layer: "composition",
    description: "+/- 스테퍼와 min/max/step을 갖춘 숫자 입력입니다.",
    status: "done",
  },
  {
    slug: "color-picker",
    title: "Color Picker",
    category: "form",
    layer: "composition",
    description: "프리셋 스와치 그리드 + hex 입력 + 미리보기의 순수 색상 선택기입니다(외부 라이브러리 없음).",
    status: "done",
  },
  {
    slug: "rating",
    title: "Rating",
    category: "data",
    layer: "composition",
    description: "별점 — hover 프리뷰·반개·readonly를 지원합니다.",
    status: "done",
  },
  {
    slug: "avatar-group",
    title: "Avatar Group",
    category: "data",
    layer: "composition",
    description: "겹친 아바타 스택 + 초과 시 +N 오버플로입니다.",
    status: "done",
  },
  {
    slug: "circular-progress",
    title: "Circular Progress",
    category: "data",
    layer: "composition",
    description: "순수 SVG 링 진행률(중앙 라벨·size/stroke)입니다.",
    status: "done",
  },
  {
    slug: "banner",
    title: "Banner",
    category: "data",
    layer: "composition",
    description: "info/success/warning/destructive variant 공지 바(닫기)입니다.",
    status: "done",
  },
  {
    slug: "code-block",
    title: "Code Block",
    category: "data",
    layer: "composition",
    description: "복사 버튼과 라인번호를 갖춘 코드 블록입니다(외부 하이라이터 없음).",
    status: "done",
  },
  {
    slug: "tree-view",
    title: "Tree View",
    category: "data",
    layer: "composition",
    description: "폴더/파일 아이콘·키보드 접근성을 갖춘 범용 접이식 트리입니다.",
    status: "done",
  },
  {
    slug: "relation-network",
    title: "Relation Network",
    category: "data",
    layer: "composition",
    description: "노드·엣지 데이터를 성좌 형태로 그리는 순수 SVG 관계 네트워크 시각화입니다.",
    status: "done",
  },
  {
    slug: "risk-core-map",
    title: "Risk Core Map",
    category: "finance",
    layer: "composition",
    description: "위험등급(tier)을 중심→외곽 동심원 밴드로 배치하고 노드 크기·글로우로 익스포저와 위험을 표현하는 리스크 코어 네트워크 맵입니다.",
    status: "done",
  },
  {
    slug: "scenario-simulator",
    title: "Scenario Simulator",
    category: "finance",
    layer: "composition",
    description: "파라미터 선택에 따라 현재/시나리오/증가분 KPI 카드가 즉시 재계산되는 what-if 시나리오 시뮬레이터입니다.",
    status: "done",
  },
  {
    slug: "pipeline-rail",
    title: "Pipeline Rail",
    category: "layout",
    layer: "composition",
    description: "원형 번호 노드 레일과 서브탭 2단으로 프로세스 단계를 탐색하는 파이프라인 스텝퍼입니다. 제외 단계는 점선·비활성으로 표시합니다.",
    status: "done",
  },
  {
    slug: "stage-progress-board",
    title: "Stage Progress Board",
    category: "data",
    layer: "composition",
    description: "단계별 상태 배지·진행 바·작업 체크리스트를 카드 그리드로 보여주는 다단계 진행 현황 보드입니다.",
    status: "done",
  },
  {
    slug: "keyword-cloud",
    title: "Keyword Cloud",
    category: "data",
    layer: "composition",
    description: "빈도를 3단계 티어의 pill 크기·강조로 표현하고 클릭 시 관련 항목을 펼치는 키워드 클라우드입니다.",
    status: "done",
  },
  {
    slug: "contribution-bars",
    title: "Contribution Bars",
    category: "data",
    layer: "composition",
    description: "요인별 기여도를 트랙 바와 퍼센트로 분해해 보여주는 SHAP 스타일 기여도 패널입니다.",
    status: "done",
  },
  {
    slug: "live-indicator",
    title: "Live Indicator",
    category: "data",
    layer: "composition",
    description: "live/paused/stale/offline 상태를 펄스 도트와 갱신 시각으로 보여주는 실시간 상태 인디케이터입니다.",
    status: "done",
  },
  {
    slug: "mermaid-viewer",
    title: "Mermaid Viewer",
    category: "data",
    layer: "composition",
    description: "mermaid 코드를 동적 로드로 SVG 렌더링하는 다이어그램 뷰어입니다. 코드펜스 스트립과 다크모드, 로딩·에러 상태를 지원합니다.",
    status: "done",
  },
  {
    slug: "icon-picker",
    title: "Icon Picker",
    category: "form",
    layer: "composition",
    description: "Phosphor 아이콘을 카테고리 탭과 한글/영문 통합 검색으로 고르는 팝오버 선택기입니다(srope 이식).",
    status: "done",
  },
  {
    slug: "app-logo",
    title: "App Logo",
    category: "layout",
    layer: "composition",
    description: "primary 배경 타일 위에 Phosphor 아이콘을 올린 앱 로고입니다. 로그인·사이드바 헤더 공용(srope 이식).",
    status: "done",
  },
  {
    slug: "empty-state",
    title: "Empty State",
    category: "layout",
    layer: "composition",
    description: "message/icon/subtext/action prop API 하나로 끝나는 빈 상태 편의 래퍼입니다(srope 이식).",
    status: "done",
  },
  {
    slug: "error-state",
    title: "Error State",
    category: "layout",
    layer: "composition",
    description: "page(카드+재시도)/inline(폼 박스)/simple(한 줄) 3변형 에러 상태입니다(srope 이식).",
    status: "done",
  },
  {
    slug: "confirm-dialog",
    title: "Confirm Dialog",
    category: "overlay",
    layer: "composition",
    description: "삭제·초기화 등 되돌릴 수 없는 작업 전 확인 전용 AlertDialog 래퍼입니다. loading 시 확인 버튼 잠금(srope 이식).",
    status: "done",
  },
  {
    slug: "badge-with-spinner",
    title: "Badge with Spinner",
    category: "data",
    layer: "composition",
    description: "배지 좌측에 회전 스피너를 붙여 진행 중 상태를 표시합니다. badge-extended variant 를 따릅니다(srope 이식).",
    status: "done",
  },
  {
    slug: "summary-card",
    title: "Summary Card",
    category: "data",
    layer: "composition",
    description: "아이콘 + 라벨 + 숫자 + 단위의 대시보드 KPI 요약 타일입니다(srope 이식).",
    status: "done",
  },
  {
    slug: "status-card",
    title: "Status Card",
    category: "data",
    layer: "composition",
    description: "이름 + 상태 배지 + 진행률 바 카드 — variant 하나로 배지·바 색이 함께 정해집니다(srope 이식).",
    status: "done",
  },
  {
    slug: "action-card",
    title: "Action Card",
    category: "data",
    layer: "composition",
    description: "아이콘 + 제목 + 설명 + CTA 버튼의 기능 진입 카드입니다(srope 이식).",
    status: "done",
  },
  {
    slug: "category-card",
    title: "Category Card",
    category: "data",
    layer: "composition",
    description: "아이콘 + 라벨 + 합계 + 하위 항목 리스트의 분류 집계 카드입니다(srope 이식).",
    status: "done",
  },
  {
    slug: "gauge-card",
    title: "Gauge Card",
    category: "data",
    layer: "composition",
    description: "이름 + 상태 배지 + 임계 기반 게이지 바 + 태그·원인 태그 카드입니다. 60/30 임계로 색이 자동 결정됩니다(srope 이식).",
    status: "done",
  },
  {
    slug: "page-header",
    title: "Page Header",
    category: "layout",
    layer: "composition",
    description: "페이지 타이틀(h1) + 우측 배지/액션 슬롯 + 설명의 페이지 상단 헤더입니다(srope 이식).",
    status: "done",
  },
  {
    slug: "scroll-stack",
    title: "Scroll Stack",
    category: "layout",
    layer: "composition",
    description: "스크롤에 따라 카드가 상단에 핀 고정되며 겹겹이 쌓이는 스크롤 연동 스택입니다. scale·회전·블러 강도를 props 로 조절합니다.",
    status: "done",
  },
  {
    slug: "signal-card",
    title: "Signal Card",
    category: "finance",
    layer: "composition",
    description: "종목명 + verdict 배지 + 매수/보유/매도 3단 점수 바의 매매 시그널 카드입니다(srope 이식).",
    status: "done",
  },
  {
    slug: "chat-widget",
    title: "Chat Widget",
    category: "chat",
    layer: "composition",
    description: "우하단 런처 + 미읽음 배지 + 말풍선/귓속말/시스템 메시지 패널의 플로팅 채팅 위젯입니다. 실시간 연동은 호출부 소유(srope 이식).",
    status: "done",
  },
]

export function getComponentEntry(slug: string): ComponentEntry | undefined {
  return COMPONENT_REGISTRY.find((entry) => entry.slug === slug)
}
